build-steps:
  - build:
      type: script
      script:
        - composer install --no-progress
        - echo "require('/var/www/site-php/${PIPELINE_CLOUD_SITE}/${PIPELINE_CLOUD_SITE}-settings.inc');" >> docroot/sites/default/settings.php
        # See DPL-286
        - echo '\$settings["install_profile"] = "";' >> docroot/sites/default/settings.php

