build-steps:
  -
    pipeline:
      type: script
      script:
      # Run composer install to get access the private acquia buildstepstutorial repository with the secret.txt file
        - 'composer --no-interaction --quiet install'

